/**
 * Central portfolio data/configuration.
 * Everything the UI renders comes from this file — edit here, not in index.html.
 */

const portfolioData = {

  personal: {
    name: "Kamal El Sayyed",
    title: "Software Engineer",
    tagline: "Mobile, Full-Stack & DevOps",
    location: "Beirut, Lebanon",
    photo: "assets/images/profile.jpg",
    cvPath: "cv/Kamal-Sayed.pdf",
    email: "kamal.sayed16@gmail.com",
    phone: "+961 81 615 908",
  },

  seo: {
    title: "Kamal El Sayyed. Software Engineer (Mobile, Full-Stack & DevOps)",
    description:
      "Portfolio of Kamal El Sayyed, a software engineer with 7 years of experience across mobile, full-stack, and DevOps engineering.",
  },

  social: [
    { id: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/kamal-el-sayyed", icon: "linkedin", order: 1, visible: true },
    { id: "email", label: "Email", url: "mailto:kamal.sayed16@gmail.com", icon: "mail", order: 2, visible: true },
  ],

  hero: {
    specialties: ["Mobile Engineering", "Full-Stack Development", "DevOps & Cloud"],
    intro:
      "I build across the whole stack: mobile apps, backend services, and the cloud infrastructure that ships them. Seven years in, I've learned every layer well enough to move between them on demand, and to know exactly where AI-assisted tooling helps and where it needs a second look from someone who understands the system.",
  },

  about: {
    paragraphs: [
      "I'm a full-stack engineer with 7 years of experience spanning mobile, frontend, backend, cloud, and DevOps. I've moved between these areas whenever a team needed it, which means I'm comfortable picking up unfamiliar ground quickly rather than staying in one lane.",
      "AI is now a normal part of how I build and review code. I use it to speed up development, debugging, and code review, but I only ship what I've personally read and understood, because I'm the one accountable for it.",
      "Recent work has centered on outsourced engineering for enterprise and startup clients: building AI-assisted development workflows, automating cloud infrastructure with Terraform and AWS CDK, and moving legacy integrations to event-driven architectures.",
    ],
  },

  whatIDo: [
    {
      id: "mobile",
      order: 1,
      visible: true,
      title: "Mobile Development",
      description:
        "Production mobile applications built with Flutter and Dart, plus native Android (Java, Android SDK) and iOS (Swift, SwiftUI) experience, from full app rebuilds to modular, reusable codebases.",
      icon: "smartphone",
    },
    {
      id: "fullstack",
      order: 2,
      visible: true,
      title: "Full-Stack Development",
      description:
        "End-to-end web applications with FastAPI and ASP.NET Core backends, SQL and NoSQL data layers, and third-party integrations for payments, calendars, and banking systems.",
      icon: "layers",
    },
    {
      id: "devops",
      order: 3,
      visible: true,
      title: "DevOps & Cloud",
      description:
        "Infrastructure as Code with Terraform and AWS CDK, automated Cloud Build pipelines, and observability with Datadog, reducing deployment time and manual release work.",
      icon: "cloud",
    },
  ],

  companies: [
    {
      id: "cloudgate",
      name: "Cloudgate Consulting",
      type: "employer",
      logo: null,
      location: "USA / Canada (Remote)",
    },
    {
      id: "telus-health",
      name: "TELUS Health",
      type: "client",
      parentCompanyId: "cloudgate",
      logo: null,
      location: "Canada / USA / Australia",
    },
    {
      id: "fennel",
      name: "Fennel",
      type: "client",
      parentCompanyId: "cloudgate",
      logo: null,
      location: null,
    },
    {
      id: "awt",
      name: "A World Technologies",
      type: "employer",
      logo: null,
      location: "Aley, Lebanon",
    },
    {
      id: "finfirst",
      name: "FinFirst Capital",
      type: "employer",
      logo: null,
      location: "Kuwait (Remote)",
    },
    {
      id: "quayo",
      name: "Quayo Mobility Solutions",
      type: "employer",
      logo: null,
      location: "Beirut, Lebanon",
    },
  ],

  experience: [
    {
      id: "exp-cloudgate",
      order: 1,
      visible: true,
      companyId: "cloudgate",
      role: "Senior Full Stack Developer",
      startDate: "2022-08",
      endDate: null,
      current: true,
      location: "USA / Canada (Remote)",
      summary:
        "Building outsourcing solutions in an Agile/Scrum setup with cross-functional teams, for clients including TELUS Health (health technology, 10,000+ employees across Canada, the US, and Australia) and Fennel (an investing app that turns ESG and shareholder data into something people can actually read).",
      achievements: [
        "Brought AI-assisted development into the team's daily work with Claude Code and custom CLAUDE.md rule files, so the assistant writes, refactors, and reviews code against our own standards, including error debugging through log-based investigation.",
        "Built an AI log-triage workflow that picks up ERROR-severity events from GCP logs, asks Gemini whether it's a real problem or noise, then opens a Jira ticket and starts the investigation, removing most manual triage.",
        "Added an AI decision step to the production release pipeline that reads the change set and decides whether maintenance mode is needed before deploying, removing a manual judgment call from releases.",
        "Automated Cloud Build pipelines for infrastructure provisioning and added AI-assisted checks into CI code review.",
        "Moved legacy REST integrations (Trafix, Stripe, Apex) to an event-driven architecture and added a WebSocket service for real-time updates with third-party systems.",
        "Integrated Datadog and used log-based tracing to find bottlenecks, reducing API response time by 20%.",
        "Introduced Infrastructure as Code with AWS CDK, cutting deployment time by 30%, and reworked the GCP–Terraform setup to cover modern and legacy infrastructure, bringing manual deployment work down to 5%.",
      ],
      technologies: ["Python", "FastAPI", "GCP", "AWS CDK", "Terraform", "DynamoDB", "Datadog", "Flutter", "Claude Code", "Gemini API"],
    },
    {
      id: "exp-awt",
      order: 2,
      visible: true,
      companyId: "awt",
      role: "Senior Software Engineer",
      startDate: "2021-08",
      endDate: "2022-08",
      current: false,
      location: "Aley, Lebanon",
      summary:
        "Backend engineer in an Agile/Scrum team on Matensa, a financial social app that moved physical financial activity into digital processes: agreements, invoices, marketplace, reservations, ticketing, and cash-in/cash-out channels.",
      achievements: [
        "Set up a proper development lifecycle: task management, branching, code reviews, automated CI/CD triggers, lifting both team output and code quality.",
        "Cut server-side latency by 10% on legacy SQL-backed applications by adding server-side caching.",
        "Integrated third-party providers for payment gateways, digital wallets, gift cards, Google Calendar APIs, and banking systems.",
        "Mocked third-party services so the full integration test suite could still run during outages, cutting test time by 50% (20 minutes to 10).",
        "Raised automated unit test coverage above 85%, cutting bugs reported by QA and users by 30–40%.",
        "Added reporting dashboards by feeding internal query results into Zoho for clearer operational insight.",
      ],
      technologies: ["C#", ".NET Core", "SQL", "PostgreSQL", "Azure"],
    },
    {
      id: "exp-finfirst",
      order: 3,
      visible: true,
      companyId: "finfirst",
      role: "Mobile Developer",
      startDate: "2020-12",
      endDate: "2021-08",
      current: false,
      location: "Kuwait (Remote)",
      summary: "Worked on an application for bank loan applications at car dealerships.",
      achievements: [
        "Led a team of 3 developers through a full rebuild of the mobile app in Flutter for iOS and Android, delivered in 60% less time than the original one-year, Android-only project.",
        "Restructured the codebase into modular libraries so the work could be reused on other projects, including CarGet, a proposal app for third-party clients.",
        "Added ASR (speech recognition) and OCR (text recognition) to the eKYC flow so customers could finish identity checks from their phone.",
      ],
      technologies: ["Dart", "Flutter", "Java", "Android SDK"],
    },
    {
      id: "exp-quayo",
      order: 4,
      visible: true,
      companyId: "quayo",
      role: "Full Stack Developer",
      startDate: "2019-09",
      endDate: "2020-10",
      current: false,
      location: "Beirut, Lebanon",
      summary: null,
      achievements: [
        "Built and launched e-commerce applications independently in 3 countries (Tunisia, Algeria, and Lebanon), owning both the frontend and the backend.",
      ],
      technologies: ["C#", ".NET Core", "Dart", "Flutter", "MS SQL", "DevExpress", "Firebase"],
    },
  ],

  /**
   * Project entry schema:
   * id, order, visible, featured, name, companyId (optional — omit for independent/
   * freelance work), context (optional fallback label when there's no companyId,
   * e.g. a client name with no dedicated company record), type (engagement type
   * shown next to the context, e.g. "Client Project", "Independent Project"),
   * overview, purpose (optional), role, contributions[], functionality[] (optional),
   * technologies[], integrations[] (optional), categories[], screenshots[] (each
   * {src, type: "mobile"|"desktop", alt, caption}), links: {liveUrl, githubUrl,
   * appStoreUrl, playStoreUrl}.
   */
  projects: [
    {
      id: "proj-wasselli",
      order: 1,
      visible: true,
      featured: true,
      name: "Wasselli",
      companyId: null,
      context: null,
      type: "Independent / Freelance Project",
      overview:
        "Wasselli is a multi-application delivery platform built around every participant in the delivery lifecycle: dedicated Client, Driver, Store, and Admin applications working together as one ecosystem.",
      purpose:
        "To connect customers, delivery drivers, participating stores, and platform administrators within a single coordinated delivery ecosystem.",
      role: "End-to-End Developer",
      contributions: [
        "Delivered the platform end-to-end across all four applications, Client, Driver, Store, and Admin, rather than a single isolated feature.",
        "Built the Flutter front-ends for each application alongside the Python backend that powers them.",
        "Connected the backend to Firebase Authentication and Cloud Firestore for user management and real-time data.",
      ],
      functionality: [
        "Customer-facing ordering experience via the Client app",
        "Delivery driver operations via the Driver app",
        "Store-side order and participation management via the Store app",
        "Centralized administrative control via the Admin app",
      ],
      technologies: ["Flutter", "Python", "Firebase Authentication", "Cloud Firestore"],
      integrations: [],
      categories: ["Mobile", "Flutter", "Backend", "Firebase", "DevOps", "End-to-End Development"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-fennel",
      order: 2,
      visible: true,
      featured: true,
      name: "Fennel",
      companyId: "fennel",
      context: null,
      type: "Client Engagement",
      overview:
        "Fennel is an investment platform structured across four engineering areas: Mobile, Backend, Brokerage, and Admin Portal. Turning ESG and shareholder data into something people can actually read.",
      purpose:
        "To give everyday investors clear visibility into ESG and shareholder information alongside core brokerage functionality.",
      role: "Full Stack Developer — Brokerage & Admin Portal",
      contributions: [
        "Built the integration layer connecting the platform to third-party brokerage services.",
        "Contributed to the Admin Portal used to operate and manage the platform.",
      ],
      functionality: [
        "Market data and stock price retrieval",
        "Stock purchasing / trading functionality",
        "AML (anti-money-laundering) checks via third-party providers",
        "Administrative portal for platform operations",
      ],
      technologies: ["Python", "FastAPI", "GCP", "DynamoDB"],
      integrations: ["AML compliance provider", "Market data / stock price provider", "Brokerage / trade execution service"],
      categories: ["Flutter", "Backend", "FinTech", "Third-Party Integrations", "DevOps"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-matensa",
      order: 3,
      visible: true,
      featured: false,
      name: "Matensa",
      companyId: "awt",
      context: null,
      type: "Client Project",
      overview:
        "Matensa is the flagship application for A World Technologies (Arab World Innovation Technologies), a financial social app that moves physical financial activity into digital processes: agreements, invoices, marketplace, reservations, ticketing, and cash-in/cash-out channels.",
      purpose: null,
      role: "Backend Engineer — Third-Party Integrations",
      contributions: [
        "Owned backend integrations connecting the platform with external financial and service providers, including BLOM, LGB, Whish Money, Ihjoz, and gift-card providers.",
        "Set up the team's development lifecycle: task management, branching strategy, code reviews, and automated CI/CD triggers.",
        "Reduced server-side latency by 10% on legacy SQL-backed applications with server-side caching.",
        "Mocked third-party services to keep the integration test suite running during outages, cutting test time from 20 to 10 minutes.",
        "Raised automated unit test coverage above 85%, cutting bugs reported by QA and users by 30–40%.",
        "Built reporting dashboards by feeding internal query results into Zoho.",
      ],
      functionality: [
        "Digital agreements and invoicing",
        "Marketplace",
        "Reservations and ticketing",
        "Cash-in / cash-out channels",
      ],
      technologies: ["C#", ".NET Core", "SQL", "PostgreSQL", "Azure"],
      integrations: ["BLOM", "LGB", "Whish Money", "Ihjoz", "Gift-card providers"],
      categories: ["Backend", "Third-Party Integrations", "FinTech", "DevOps"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-rapids",
      order: 4,
      visible: true,
      featured: true,
      name: "RAPIDS",
      companyId: "telus-health",
      context: null,
      type: "Internal Platform",
      overview:
        "RAPIDS is an internal engineering platform I support as part of my role at TELUS Health, focused on the operational side of running production software, keeping deployments, infrastructure, and monitoring reliable.",
      purpose: null,
      role: "DevOps / Reliability Contributor",
      contributions: [
        "Own responsibilities spanning deployments, monitoring, GitHub repository management, analytics, backups, and infrastructure.",
        "Support the operational and reliability requirements needed to keep a production software environment running smoothly, beyond application development alone.",
      ],
      functionality: [],
      technologies: ["GCP", "AWS CDK", "Terraform", "Cloud Build", "Datadog", "CI/CD"],
      integrations: [],
      categories: ["DevOps"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-finfirst",
      order: 5,
      visible: true,
      featured: true,
      name: "FinFirst",
      companyId: "finfirst",
      context: null,
      type: "Client Project",
      overview: "FinFirst is a mobile application for bank loan applications by going through the eKYC process and uploading the required document per each bank.",
      purpose: null,
      role: "Mobile Developer",
      contributions: [
        "Led a team of 3 developers through a full rebuild of the app in Flutter for iOS and Android, delivered in 60% less time than the original one-year, Android-only project.",
        "Restructured the codebase into modular libraries so the work could be reused on other projects.",
        "Added ASR (speech recognition) and OCR (text recognition) to the eKYC flow so customers could finish identity checks from their phone.",
      ],
      functionality: [],
      technologies: ["Dart", "Flutter", "Java", "Android SDK"],
      integrations: [],
      categories: ["Mobile"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-carget",
      order: 6,
      visible: true,
      featured: false,
      name: "CarGet",
      companyId: "finfirst",
      context: null,
      type: "Client Project",
      overview:
        "CarGet is a mobile application for car dealers to manage and present their vehicle inventory, including listing cars, detailed vehicle specifications, and side-by-side comparisons between two vehicles.",
      purpose: null,
      role: "Mobile Developer",
      contributions: [
        "Built the mobile application using the modular Flutter library structure established during the FinFirst rebuild, accelerating delivery.",
      ],
      functionality: [
        "Vehicle listing for dealers",
        "Detailed vehicle specifications",
        "Side-by-side comparison of two vehicles",
      ],
      technologies: ["Dart", "Flutter"],
      integrations: [],
      categories: ["Mobile", "Flutter"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-checkpoint",
      order: 7,
      visible: true,
      featured: true,
      name: "Checkpoint",
      companyId: null,
      context: "King Abdulaziz University — Saudi Arabia",
      type: "Freelance / Client Project",
      overview:
        "Checkpoint is an administration and attendance-management application used by King Abdulaziz University (Saudi Arabia) to manage the relationships between courses, instructors, and students.",
      purpose: null,
      role: "End-to-End Developer",
      contributions: [
        "Delivered the application end-to-end, from administrative course, instructor, and student management flows to student-facing attendance recording.",
      ],
      functionality: [
        "Create and manage courses, instructors, and students",
        "Assign instructors to courses and manage course participation",
        "Record student attendance by scanning the student's QR code",
      ],
      technologies: ["Flutter", "Firebase Authentication", "Cloud Firestore"],
      integrations: [],
      categories: ["Mobile", "Flutter", "Firebase", "End-to-End Development"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-beefarmer",
      order: 8,
      visible: true,
      featured: false,
      name: "BeeFarmer",
      companyId: null,
      context: null,
      type: "Independent / Freelance Project",
      overview: "BeeFarmer is a mobile application for managing beehives and related operational information.",
      purpose: null,
      role: "End-to-End Developer",
      contributions: [
        "Delivered the application end-to-end, covering the full mobile experience for managing hives and related operational information.",
      ],
      functionality: ["Beehive and operational record management"],
      technologies: ["Flutter", "Firebase Authentication", "Cloud Firestore"],
      integrations: [],
      categories: ["Mobile", "Flutter", "Firebase", "End-to-End Development"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-forza",
      order: 9,
      visible: true,
      featured: false,
      name: "Forza",
      companyId: null,
      context: null,
      type: "Independent / Freelance Project",
      overview: "Forza is a mobile application for managing internet subscriptions.",
      purpose: null,
      role: "End-to-End Developer",
      contributions: [
        "Delivered the application end-to-end to support internet subscription management workflows.",
      ],
      functionality: ["Internet subscription management"],
      technologies: ["Flutter", "Firebase Authentication", "Cloud Firestore"],
      integrations: [],
      categories: ["Mobile", "Flutter", "Firebase", "End-to-End Development"],
      screenshots: [],
      links: {},
    },
    {
      id: "proj-realsteel",
      order: 10,
      visible: true,
      featured: false,
      name: "RealSteel",
      companyId: null,
      context: null,
      type: "Independent / Freelance Project",
      overview: "RealSteel is a gym subscription and management application supporting gym operations and member-related workflows.",
      purpose: null,
      role: "End-to-End Developer",
      contributions: [
        "Delivered the application end-to-end across membership, attendance, and inventory workflows.",
      ],
      functionality: [
        "Gym subscription and membership management",
        "Attendance scanning",
        "Stock / inventory management",
      ],
      technologies: ["Flutter", "Firebase Authentication", "Cloud Firestore"],
      integrations: [],
      categories: ["Mobile", "Flutter", "Firebase", "End-to-End Development"],
      screenshots: [],
      links: {},
    },
  ],

  skills: [
    {
      id: "ai",
      order: 1,
      visible: true,
      category: "AI & LLMs",
      items: [
        "Claude Code & Claude Desktop",
        "Gemini API",
        "ChatGPT",
        "Prompt Engineering",
        "Context Engineering (CLAUDE.md rules)",
        "LLM API Integration",
        "AI-Assisted Code Review",
        "AI-Driven Log Analysis",
      ],
    },
    {
      id: "languages",
      order: 2,
      visible: true,
      category: "Languages",
      items: ["Python", "Dart", "C#", "Bash Scripting", "Java", "Swift"],
    },
    {
      id: "frameworks",
      order: 3,
      visible: true,
      category: "Frameworks",
      items: ["FastAPI", "ASP.NET Core", "Flutter", "Unity", "Android SDK", "SwiftUI"],
    },
    {
      id: "databases",
      order: 4,
      visible: true,
      category: "Databases",
      items: ["SQL (MSSQL, PostgreSQL)", "NoSQL (Cloud Firestore, DynamoDB)", "GraphDB (Neo4j)"],
    },
    {
      id: "cloud-devops",
      order: 5,
      visible: true,
      category: "Cloud & DevOps",
      items: ["GCP", "AWS", "Azure", "Terraform", "AWS CDK", "Docker", "Cloud Build", "CI/CD"],
    },
    {
      id: "tools",
      order: 6,
      visible: true,
      category: "Tools",
      items: ["Datadog", "Firebase", "Kong Gateway", "Ansible", "PagerDuty", "Jira"],
    },
  ],

  education: [
    {
      id: "edu-lebanese-university",
      order: 1,
      visible: true,
      institution: "Lebanese University",
      degree: "Bachelor's Degree in Computer Science",
      startDate: "2016-10",
      endDate: "2019-08",
    },
  ],

  certifications: [],

  contact: {
    heading: "Let's Talk",
    message:
      "I'm always open to discussing new projects, engineering challenges, or opportunities to collaborate.",
  },
};
